tax: 0.0
auction-setup-time: 30
default-max-auctions: 10
sold-message: true
auto-collect: false
partial-selling: false
admin-permission: auctionhouse.moderator
display-update: 20
auction-announcements: true
bin-auctions: true
bin-auction-duration: 172800
min-bin: 1
bid-auctions: true
bid-auction-duration: 7200
min-bid: 1
last-bid-extra-time: 60
bid-increase-percent: 25
displays:
  highest_price:
    '1':
      glass: WHITE_STAINED_GLASS
      base: RESPAWN_ANCHOR:4 # Supports any block with a data value
      sign: DARK_OAK_WALL_SIGN
    '2':
      glass: WHITE_STAINED_GLASS
      base: LODESTONE
      sign: DARK_OAK_WALL_SIGN
    default:
      glass: WHITE_STAINED_GLASS
      base: CHISELED_TUFF
      sign: DARK_OAK_WALL_SIGN
  ending_soon:
    '1':
      glass: YELLOW_STAINED_GLASS
      base: GOLD_BLOCK
      sign: DARK_OAK_WALL_SIGN
    '2':
      glass: WHITE_STAINED_GLASS
      base: LODESTONE
      sign: DARK_OAK_WALL_SIGN
    default:
      glass: WHITE_STAINED_GLASS
      base: CHISELED_TUFF
      sign: DARK_OAK_WALL_SIGN
plugin-version: 1.4.4
